import { DRIFTLANDS_PALETTE } from "../palette.js";
import type { ArtifactDefinition } from "../types.js";
import { ArtifactCatalogSchema } from "../schemas.js";

/** V1 artifact catalog — config-driven; balance without code changes. */
export const ARTIFACT_CATALOG_RAW = {
  config_version: "artifacts-v1.0.0",
  artifacts: [
    {
      artifact_id: "armor_sunweave",
      category: "armor" as const,
      rank: "common" as const,
      rank_tier: 1,
      survival_modifier: 0.06,
      modifier_type: "general_survival" as const,
      stack_limit: 1,
      drop_weight: 0.22,
      min_journey_zone: 0,
      revive_discount: 0,
      flavor_text: "Light weave that catches the desert glare.",
      display_name: "Sunweave Vest",
      color: DRIFTLANDS_PALETTE.sun,
    },
    {
      artifact_id: "food_cactus_nectar",
      category: "food" as const,
      rank: "common" as const,
      rank_tier: 1,
      survival_modifier: 0.05,
      modifier_type: "general_survival" as const,
      stack_limit: 3,
      drop_weight: 0.28,
      min_journey_zone: 0,
      revive_discount: 0,
      flavor_text: "Sweet, sticky, and surprisingly steadying.",
      display_name: "Cactus Nectar",
      color: DRIFTLANDS_PALETTE.success,
    },
    {
      artifact_id: "tool_drift_pick",
      category: "tool" as const,
      rank: "uncommon" as const,
      rank_tier: 2,
      survival_modifier: 0.12,
      modifier_type: "resource_boost" as const,
      stack_limit: 1,
      drop_weight: 0.14,
      min_journey_zone: 1,
      revive_discount: 0,
      flavor_text: "Pulls caches out of dunes like magnets.",
      display_name: "Drift Pick",
      color: DRIFTLANDS_PALETTE.turquoise,
    },
    {
      artifact_id: "charm_ember_ward",
      category: "charm" as const,
      rank: "rare" as const,
      rank_tier: 3,
      survival_modifier: 0.18,
      modifier_type: "fire_hazard_resist" as const,
      stack_limit: 1,
      drop_weight: 0.08,
      min_journey_zone: 2,
      revive_discount: 0,
      flavor_text: "Warm to the touch, even underwater.",
      display_name: "Ember Ward",
      color: DRIFTLANDS_PALETTE.coral,
    },
    {
      artifact_id: "charm_stormglass",
      category: "charm" as const,
      rank: "rare" as const,
      rank_tier: 3,
      survival_modifier: 0.2,
      modifier_type: "storm_resist" as const,
      stack_limit: 1,
      drop_weight: 0.07,
      min_journey_zone: 2,
      revive_discount: 0,
      flavor_text: "A shard that still hums with last night's gale.",
      display_name: "Stormglass Charm",
      color: DRIFTLANDS_PALETTE.sky,
    },
    {
      artifact_id: "armor_mirage_plate",
      category: "armor" as const,
      rank: "epic" as const,
      rank_tier: 4,
      survival_modifier: 0.28,
      modifier_type: "ambush_resist" as const,
      stack_limit: 1,
      drop_weight: 0.04,
      min_journey_zone: 3,
      revive_discount: 0.05,
      flavor_text: "Looks like heat shimmer until it stops a blade.",
      display_name: "Mirage Plate",
      color: DRIFTLANDS_PALETTE.magenta,
    },
    {
      artifact_id: "charm_second_sun",
      category: "charm" as const,
      rank: "legendary" as const,
      rank_tier: 5,
      survival_modifier: 0.4,
      modifier_type: "general_survival" as const,
      stack_limit: 1,
      drop_weight: 0.015,
      min_journey_zone: 4,
      revive_discount: 0.15,
      flavor_text: "A second dawn carried in a pocket.",
      display_name: "Second Sun",
      color: DRIFTLANDS_PALETTE.sunBright,
    },
  ],
};

const parsed = ArtifactCatalogSchema.parse(ARTIFACT_CATALOG_RAW);

export const ARTIFACT_CONFIG_VERSION = parsed.config_version;

export const ARTIFACT_DEFINITIONS: ArtifactDefinition[] = parsed.artifacts.map((a) => ({
  artifactId: a.artifact_id,
  category: a.category,
  rank: a.rank,
  rankTier: a.rank_tier,
  survivalModifier: a.survival_modifier,
  modifierType: a.modifier_type,
  stackLimit: a.stack_limit,
  dropWeight: a.drop_weight,
  minJourneyZone: a.min_journey_zone,
  reviveDiscount: a.revive_discount,
  flavorText: a.flavor_text,
  displayName: a.display_name,
  color: a.color ?? DRIFTLANDS_PALETTE.sun,
}));

export function getArtifactById(id: string): ArtifactDefinition | undefined {
  return ARTIFACT_DEFINITIONS.find((a) => a.artifactId === id);
}
