import { DRIFTLANDS_PALETTE } from "../palette.js";
import type { ArtifactDefinition } from "../types.js";
import { ArtifactCatalogSchema } from "../schemas.js";

/** V1.1 artifact catalog — PRD §9 ranks + multi-stat loadouts. Wayfarer tone. */
export const ARTIFACT_CATALOG_RAW = {
  config_version: "artifacts-v1.1.0",
  artifacts: [
    {
      artifact_id: "armor_sunweave",
      category: "armor" as const,
      rank: "common" as const,
      rank_tier: 1,
      survival_modifier: 0.06,
      modifier_type: "general_survival" as const,
      stack_limit: 1,
      drop_weight: 0.2,
      min_journey_zone: 0,
      revive_discount: 0,
      flavor_text: "Cloth that still remembers noon.",
      display_name: "Sunweave Vest",
      color: DRIFTLANDS_PALETTE.sun,
      stats: { power: 8, vitality: 14, focus: 4, luck: 6, weight: 6 },
    },
    {
      artifact_id: "food_cactus_nectar",
      category: "food" as const,
      rank: "common" as const,
      rank_tier: 1,
      survival_modifier: 0.05,
      modifier_type: "general_survival" as const,
      stack_limit: 3,
      drop_weight: 0.24,
      min_journey_zone: 0,
      revive_discount: 0,
      flavor_text: "Sweet enough to hold a shape for one more mile.",
      display_name: "Cactus Nectar",
      color: DRIFTLANDS_PALETTE.success,
      stats: { power: 4, vitality: 18, focus: 2, luck: 8, weight: 2 },
    },
    {
      artifact_id: "charm_sand_token",
      category: "charm" as const,
      rank: "common" as const,
      rank_tier: 1,
      survival_modifier: 0.04,
      modifier_type: "general_survival" as const,
      stack_limit: 2,
      drop_weight: 0.18,
      min_journey_zone: 0,
      revive_discount: 0,
      flavor_text: "A coin nobody agreed was currency — yet it still buys luck.",
      display_name: "Sand Token",
      color: DRIFTLANDS_PALETTE.sand,
      stats: { power: 6, vitality: 6, focus: 6, luck: 16, weight: 1 },
    },
    {
      artifact_id: "tool_drift_pick",
      category: "tool" as const,
      rank: "uncommon" as const,
      rank_tier: 2,
      survival_modifier: 0.1,
      modifier_type: "resource_boost" as const,
      stack_limit: 1,
      drop_weight: 0.12,
      min_journey_zone: 1,
      revive_discount: 0,
      flavor_text: "Pulls caches out of dunes like a promise kept.",
      display_name: "Drift Pick",
      color: DRIFTLANDS_PALETTE.turquoise,
      stats: { power: 16, vitality: 8, focus: 12, luck: 14, weight: 10 },
    },
    {
      artifact_id: "armor_dune_wraps",
      category: "armor" as const,
      rank: "uncommon" as const,
      rank_tier: 2,
      survival_modifier: 0.1,
      modifier_type: "storm_resist" as const,
      stack_limit: 1,
      drop_weight: 0.11,
      min_journey_zone: 1,
      revive_discount: 0,
      flavor_text: "Wraps that lean into the wind instead of fighting it.",
      display_name: "Dune Wraps",
      color: DRIFTLANDS_PALETTE.sky,
      stats: { power: 12, vitality: 16, focus: 18, luck: 6, weight: 8 },
    },
    {
      artifact_id: "food_ash_biscuit",
      category: "food" as const,
      rank: "uncommon" as const,
      rank_tier: 2,
      survival_modifier: 0.08,
      modifier_type: "fire_hazard_resist" as const,
      stack_limit: 2,
      drop_weight: 0.1,
      min_journey_zone: 1,
      revive_discount: 0,
      flavor_text: "Baked where reality still argued about fire.",
      display_name: "Ash Biscuit",
      color: DRIFTLANDS_PALETTE.coral,
      stats: { power: 8, vitality: 14, focus: 16, luck: 8, weight: 3 },
    },
    {
      artifact_id: "charm_ember_ward",
      category: "charm" as const,
      rank: "rare" as const,
      rank_tier: 3,
      survival_modifier: 0.18,
      modifier_type: "fire_hazard_resist" as const,
      stack_limit: 1,
      drop_weight: 0.07,
      min_journey_zone: 2,
      revive_discount: 0,
      flavor_text: "Warm to the touch, even underwater.",
      display_name: "Ember Ward",
      color: DRIFTLANDS_PALETTE.coral,
      stats: { power: 22, vitality: 12, focus: 34, luck: 10, weight: 4 },
    },
    {
      artifact_id: "charm_stormglass",
      category: "charm" as const,
      rank: "rare" as const,
      rank_tier: 3,
      survival_modifier: 0.2,
      modifier_type: "storm_resist" as const,
      stack_limit: 1,
      drop_weight: 0.06,
      min_journey_zone: 2,
      revive_discount: 0,
      flavor_text: "A shard that still hums with last night's gale.",
      display_name: "Stormglass Charm",
      color: DRIFTLANDS_PALETTE.sky,
      stats: { power: 20, vitality: 10, focus: 36, luck: 12, weight: 3 },
    },
    {
      artifact_id: "tool_cartographer_lens",
      category: "tool" as const,
      rank: "rare" as const,
      rank_tier: 3,
      survival_modifier: 0.14,
      modifier_type: "ambush_resist" as const,
      stack_limit: 1,
      drop_weight: 0.055,
      min_journey_zone: 2,
      revive_discount: 0,
      flavor_text: "Shows the fork that wants to be believed.",
      display_name: "Cartographer Lens",
      color: DRIFTLANDS_PALETTE.turquoise,
      stats: { power: 18, vitality: 10, focus: 30, luck: 20, weight: 5 },
    },
    {
      artifact_id: "armor_mirage_plate",
      category: "armor" as const,
      rank: "epic" as const,
      rank_tier: 4,
      survival_modifier: 0.28,
      modifier_type: "ambush_resist" as const,
      stack_limit: 1,
      drop_weight: 0.035,
      min_journey_zone: 3,
      revive_discount: 0.05,
      flavor_text: "Looks like heat shimmer until it stops a blade.",
      display_name: "Mirage Plate",
      color: DRIFTLANDS_PALETTE.magenta,
      stats: { power: 34, vitality: 28, focus: 32, luck: 10, weight: 18 },
    },
    {
      artifact_id: "food_conviction_draught",
      category: "food" as const,
      rank: "epic" as const,
      rank_tier: 4,
      survival_modifier: 0.22,
      modifier_type: "general_survival" as const,
      stack_limit: 1,
      drop_weight: 0.03,
      min_journey_zone: 3,
      revive_discount: 0.08,
      flavor_text: "One sip and the Drift remembers your name.",
      display_name: "Conviction Draught",
      color: DRIFTLANDS_PALETTE.sunBright,
      stats: { power: 28, vitality: 36, focus: 16, luck: 18, weight: 4 },
    },
    {
      artifact_id: "tool_oath_compass",
      category: "tool" as const,
      rank: "epic" as const,
      rank_tier: 4,
      survival_modifier: 0.16,
      modifier_type: "general_survival" as const,
      stack_limit: 1,
      drop_weight: 0.028,
      min_journey_zone: 3,
      revive_discount: 0,
      flavor_text: "Always points toward the nearest safe ground.",
      display_name: "Oath Compass",
      color: DRIFTLANDS_PALETTE.ink,
      stats: { power: 24, vitality: 14, focus: 26, luck: 28, weight: 6 },
    },
    {
      artifact_id: "charm_second_sun",
      category: "charm" as const,
      rank: "legendary" as const,
      rank_tier: 5,
      survival_modifier: 0.38,
      modifier_type: "general_survival" as const,
      stack_limit: 1,
      drop_weight: 0.012,
      min_journey_zone: 4,
      revive_discount: 0.15,
      flavor_text: "A second dawn carried in a pocket.",
      display_name: "Second Sun",
      color: DRIFTLANDS_PALETTE.sunBright,
      stats: { power: 48, vitality: 40, focus: 28, luck: 22, weight: 8 },
    },
    {
      artifact_id: "armor_unbroken_oath",
      category: "armor" as const,
      rank: "legendary" as const,
      rank_tier: 5,
      survival_modifier: 0.35,
      modifier_type: "ambush_resist" as const,
      stack_limit: 1,
      drop_weight: 0.01,
      min_journey_zone: 4,
      revive_discount: 0.1,
      flavor_text: "Stitched from a soldier's promise nobody broke.",
      display_name: "Cloak of the Unbroken Oath",
      color: DRIFTLANDS_PALETTE.magenta,
      stats: { power: 42, vitality: 38, focus: 40, luck: 14, weight: 14 },
    },
  ],
};

const parsed = ArtifactCatalogSchema.parse(ARTIFACT_CATALOG_RAW);

export const ARTIFACT_CONFIG_VERSION = parsed.config_version;

export const ARTIFACT_DEFINITIONS: ArtifactDefinition[] = parsed.artifacts.map((a) => ({
  artifactId: a.artifact_id,
  category: a.category,
  rank: a.rank,
  rankTier: a.rank_tier,
  survivalModifier: a.survival_modifier,
  modifierType: a.modifier_type,
  stackLimit: a.stack_limit,
  dropWeight: a.drop_weight,
  minJourneyZone: a.min_journey_zone,
  reviveDiscount: a.revive_discount,
  flavorText: a.flavor_text,
  displayName: a.display_name,
  color: a.color ?? DRIFTLANDS_PALETTE.sun,
  stats: a.stats,
}));

export function getArtifactById(id: string): ArtifactDefinition | undefined {
  return ARTIFACT_DEFINITIONS.find((a) => a.artifactId === id);
}
